
from __future__ import annotations

from pathlib import Path

PROJECT_DIR = Path(__file__).resolve().parent
DATA_DIR = PROJECT_DIR / "data"
A_DATA_DIR = DATA_DIR
OUT_DIR = PROJECT_DIR / "out"
CHECKPOINT_DIR = PROJECT_DIR / "checkpoints"

COMMANDS = [
    "single-matrix",
    "multi-matrix",
    "ae-only-single",
    "ae-only-multi",
    "dmd-only-single",
    "dmd-only-multi",
    "ae-matrix-predict",
]


C_RE_MIN = -0.05
C_RE_MAX = 0.05
C_IM_MIN = -0.05
C_IM_MAX = 0.05
ESCAPE_R = 2.0

DYNAMICS_CLAMP_R = 100
TRAIN_MAX_ITERS = 40
PREDICT_EXTRA_STEPS = 20
PREDICT_ROLLOUT_CHECK_STEPS = 10

FILTER_ESCAPED_FOR_TRAINING = True
KEEP_ESCAPED_FRACTION = 0.0

SINGLE_MATRIX_SOURCE = "emotion"
SINGLE_MATRIX_INDEX = 7
SINGLE_MATRIX_C_RE_N = 128
SINGLE_MATRIX_C_IM_N = 128

MULTI_MATRIX_SOURCE = "emotion"
MULTI_MATRIX_TRAIN_COUNT = 10
MULTI_MATRIX_TEST_COUNT = 2
MULTI_MATRIX_SPLIT_SEED = 0
MULTI_MATRIX_C_RE_N = 128
MULTI_MATRIX_C_IM_N = 128
MULTI_MATRIX_SAVE_FULL_FIRST = True

LATENT_DIM = 256
AE_EPOCHS = 60
AE_ONLY_EPOCHS = 60
AE_BATCH_SIZE = 2048
AE_LR = 1e-4
AE_REC_WEIGHT = 1.0
AE_PRED_WEIGHT = 2.0
AE_LATENT_WEIGHT = 0.5
AE_PRED_USE_ALIVE_ONLY = True

AE_LOSS_AUTO_SCALE = True

AE_USE_LR_SCHEDULER = True
AE_LR_PATIENCE = 5
AE_LR_FACTOR = 0.5
AE_LR_MIN = 1e-6

AE_VAL_FRACTION = 0.1
AE_VAL_SEED = 0
AE_EARLY_STOP_PATIENCE = 0

AE_PRED_LATENT_DIM = LATENT_DIM
AE_PRED_EPOCHS = AE_ONLY_EPOCHS
AE_ONLY_BATCH_SIZE = AE_BATCH_SIZE
AE_ONLY_LR = AE_LR  # LR -> AE-ONLY PREDICTOR
AE_PRED_TRAIN_CLIP_R = DYNAMICS_CLAMP_R  # CLAMP -> BLD

AE_USE_QUADRATIC_PREDICTOR = False  # TOGGLE FOR QUAD-PRED INSTEAD OF ENC-DEC
AE_QUADRATIC_RANK = None  # None = FULL d x d COUPLING MATRIX; INT = LOW-RANK U V FACTORISATION

#  DMD SETTINGS 
DMD_RIDGE = 1e-2
DMD_FIT_BATCH_SIZE = 65536
AE_ENCODE_BATCH_SIZE = 65536
PREDICT_BATCH_SIZE = 4096

#  DISPLAY SAVE
IMAGE_SCALE = 4
LOSS_DPI = 160
SAVE_CSV_DMD = True
LOSS_CURVES_LOG_SCALE = True  # DEFAULT y-AXIS SCALE FOR save_loss_curve

# DEVICE
USE_CUDA_IF_AVAILABLE = True

#===V26==